
	SELECT * FROM SGR.USUARIOS U, SGR.ALUNO A, SGR.ENDERECO E WHERE U.CPF = '13352738750' AND SENHA = 'senha' and U.id_endereco = E.id_endereco;

	SELECT * FROM SGR.USUARIOS U WHERE U.CPF = '13352738750' AND SENHA = 'senha'


	SELECT * FROM SGR.REQUERIMENTOS R WHERE R.id_usuario = (SELECT id_usuario from SGR.USUARIOS U WHERE U.CPF = '13352738750')