/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static controller.Gerenciador.obterAluno;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.time.format.DateTimeFormatter;
import model.entity.Aluno;
import model.entity.Usuario;

/**
 *
 * @author tsuba
 */
public class DadosCadastraisCompletos extends javax.swing.JFrame {

    /**
     * Creates new form dadosCadastraisCompleto
     */
    public DadosCadastraisCompletos() {
        initComponents();
    }
    Aluno aluno;

    public DadosCadastraisCompletos(Aluno aluno) {
        initComponents();
        this.aluno = aluno;
        this.emailAluno.setText(aluno.getEmail());
        this.nomeAluno.setText(aluno.getNome());
        this.bairroAluno.setText(aluno.getBairro());
        this.cepAluno.setText(aluno.getCep());
        this.cidadeAluno.setText(aluno.getCidade());
        this.complementoAluno.setText(aluno.getComplemento());
        this.dataNasciAluno.setText(aluno.getDataNascimeto().format(DateTimeFormatter.ofPattern("dd-MMM-yyyy")));
        this.deficienciaAluno.setText(aluno.getDeficiencia());
        this.estadoAluno.setText(aluno.getEstado());
        this.estadoCivilAluno.setText(aluno.getEstadoCivil());
        this.lougradouroAluno.setText(aluno.getLogradouro());
        this.nacionalidadeAluno.setText(aluno.getNacionalidade());
        this.nomeMaeAluno.setText(aluno.getNomeDaMae());
        this.nomePaiAluno.setText(aluno.getNomeDoPai());
        this.numeroAluno.setText(aluno.getNumero());
        this.sexoAluno.setText(aluno.getSexo());
        this.telefoneCelularAluno.setText(aluno.getTelefoneCelular());
        this.telefoneResidencialAluno.setText(aluno.getTelefoneResidencial());
        this.tipoEnderecoAluno.setText(aluno.getTipoDeEndereco());
        this.tipoLogradouroAluno.setText(aluno.getTipoLogradouro());
        centralizarTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        nomeAluno = new javax.swing.JLabel();
        nomeMaeAluno = new javax.swing.JLabel();
        nomePaiAluno = new javax.swing.JLabel();
        nacionalidadeAluno = new javax.swing.JLabel();
        estadoCivilAluno = new javax.swing.JLabel();
        dataNasciAluno = new javax.swing.JLabel();
        deficienciaAluno = new javax.swing.JLabel();
        tipoEnderecoAluno = new javax.swing.JLabel();
        tipoLogradouroAluno = new javax.swing.JLabel();
        numeroAluno = new javax.swing.JLabel();
        bairroAluno = new javax.swing.JLabel();
        complementoAluno = new javax.swing.JLabel();
        estadoAluno = new javax.swing.JLabel();
        cepAluno = new javax.swing.JLabel();
        cidadeAluno = new javax.swing.JLabel();
        telefoneResidencialAluno = new javax.swing.JLabel();
        telefoneCelularAluno = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        lougradouroAluno = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        sexoAluno = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        paisAluno = new javax.swing.JLabel();
        emailAluno = new javax.swing.JLabel();
        okBotaoDadosCompletos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 700));

        jPanel2.setBackground(new java.awt.Color(56, 113, 156));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iBSI.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Dados Cadastrais Completos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel22)
                        .addGap(0, 90, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel22)
                        .addGap(88, 88, 88))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nome da mãe");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nome do pai");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Nascimento");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Nacionalidade");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Estado Civil");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Deficiência");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Dados Pessoais");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Endereço");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Tipo de endereço");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Tipo de Logradouro");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Número");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Complemento");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Bairro");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Cidade");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Estado");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("CEP");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Telefone Residencial");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Telefone Celular");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("E-mail");

        nomeAluno.setText("Nome Completo do Aluno");

        nomeMaeAluno.setText("Nome Completo da Mãe do Aluno");

        nomePaiAluno.setText("Nome Completo do Pai do Aluno");

        nacionalidadeAluno.setText("Nacionalidade");

        estadoCivilAluno.setText("Estado Civil");

        dataNasciAluno.setText("Data Nascimento");

        deficienciaAluno.setText("Tipo de Deficiência");

        tipoEnderecoAluno.setText("Tipo de Endereço");

        tipoLogradouroAluno.setText("Tipo de Logradouro");

        numeroAluno.setText("Número");

        bairroAluno.setText("Bairro");

        complementoAluno.setText("Complemento");

        estadoAluno.setText("Estado");

        cepAluno.setText("CEP");

        cidadeAluno.setText("Cidade");

        telefoneResidencialAluno.setText("Telefone Residencial");

        telefoneCelularAluno.setText("Telefone Celular");

        lougradouroAluno.setText("Logradouro");

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel59.setText("Logradouro");

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel60.setText("Sexo");

        sexoAluno.setText("Sexo");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("País");

        paisAluno.setText("País");

        emailAluno.setText("E-mail");

        okBotaoDadosCompletos.setText("Ok");
        okBotaoDadosCompletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBotaoDadosCompletosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel60)
                                    .addComponent(sexoAluno)
                                    .addComponent(jLabel8)
                                    .addComponent(nacionalidadeAluno)))
                            .addComponent(jLabel19))
                        .addGap(142, 142, 142)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(nomePaiAluno)
                            .addComponent(jLabel10)
                            .addComponent(deficienciaAluno)
                            .addComponent(nomeMaeAluno)))
                    .addComponent(jLabel17)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(dataNasciAluno)
                    .addComponent(jLabel9)
                    .addComponent(estadoCivilAluno)
                    .addComponent(nomeAluno)
                    .addComponent(jLabel20)
                    .addComponent(tipoEnderecoAluno)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(okBotaoDadosCompletos)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoLogradouroAluno)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel24)
                                    .addComponent(complementoAluno)
                                    .addComponent(jLabel27)
                                    .addComponent(estadoAluno)
                                    .addComponent(jLabel30)
                                    .addComponent(telefoneResidencialAluno)
                                    .addComponent(jLabel32)
                                    .addComponent(emailAluno))
                                .addGap(125, 125, 125)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lougradouroAluno)
                                    .addComponent(jLabel25)
                                    .addComponent(bairroAluno)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel26)
                                    .addComponent(cidadeAluno)
                                    .addComponent(telefoneCelularAluno)
                                    .addComponent(jLabel59))))
                        .addGap(129, 129, 129)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numeroAluno)
                            .addComponent(cepAluno)
                            .addComponent(jLabel29)
                            .addComponent(jLabel23)
                            .addComponent(jLabel36)
                            .addComponent(paisAluno))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel57)
                .addGap(0, 137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(451, 451, 451)
                            .addComponent(jLabel57))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(jLabel3)
                                    .addGap(6, 6, 6)
                                    .addComponent(nomeMaeAluno)
                                    .addGap(7, 7, 7)
                                    .addComponent(jLabel4)
                                    .addGap(6, 6, 6)
                                    .addComponent(nomePaiAluno)
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel10)
                                    .addGap(6, 6, 6)
                                    .addComponent(deficienciaAluno))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel2)
                                            .addGap(6, 6, 6)
                                            .addComponent(nomeAluno))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(64, 64, 64)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel60)
                                                    .addGap(6, 6, 6)
                                                    .addComponent(sexoAluno)
                                                    .addGap(6, 6, 6)
                                                    .addComponent(jLabel8)
                                                    .addGap(6, 6, 6)
                                                    .addComponent(nacionalidadeAluno))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addGap(6, 6, 6)
                                                    .addComponent(dataNasciAluno)
                                                    .addGap(6, 6, 6)
                                                    .addComponent(jLabel9)
                                                    .addGap(6, 6, 6)
                                                    .addComponent(estadoCivilAluno)))))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel59)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lougradouroAluno)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel25)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(bairroAluno)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel26)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cidadeAluno)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel31)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(telefoneCelularAluno))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(40, 40, 40)
                                                    .addComponent(cepAluno))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(numeroAluno)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel29)))
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel36)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(paisAluno)
                                            .addGap(21, 21, 21)))
                                    .addGap(40, 40, 40))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addGap(6, 6, 6)
                                    .addComponent(tipoEnderecoAluno)
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addComponent(complementoAluno)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel27)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(estadoAluno))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(tipoLogradouroAluno)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel24)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel30)
                                    .addGap(5, 5, 5)
                                    .addComponent(telefoneResidencialAluno)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel32)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(emailAluno)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(451, 451, 451)
                        .addComponent(okBotaoDadosCompletos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void centralizarTela() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }


    private void okBotaoDadosCompletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBotaoDadosCompletosActionPerformed

        TelaAluno janelaTelaAluno = new TelaAluno(aluno);
        janelaTelaAluno.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_okBotaoDadosCompletosActionPerformed

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bairroAluno;
    private javax.swing.JLabel cepAluno;
    private javax.swing.JLabel cidadeAluno;
    private javax.swing.JLabel complementoAluno;
    private javax.swing.JLabel dataNasciAluno;
    private javax.swing.JLabel deficienciaAluno;
    private javax.swing.JLabel emailAluno;
    private javax.swing.JLabel estadoAluno;
    private javax.swing.JLabel estadoCivilAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lougradouroAluno;
    private javax.swing.JLabel nacionalidadeAluno;
    private javax.swing.JLabel nomeAluno;
    private javax.swing.JLabel nomeMaeAluno;
    private javax.swing.JLabel nomePaiAluno;
    private javax.swing.JLabel numeroAluno;
    private javax.swing.JButton okBotaoDadosCompletos;
    private javax.swing.JLabel paisAluno;
    private javax.swing.JLabel sexoAluno;
    private javax.swing.JLabel telefoneCelularAluno;
    private javax.swing.JLabel telefoneResidencialAluno;
    private javax.swing.JLabel tipoEnderecoAluno;
    private javax.swing.JLabel tipoLogradouroAluno;
    // End of variables declaration//GEN-END:variables
}
