/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static controller.Gerenciador.obterAluno;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Date;
import model.entity.Aluno;
import model.entity.Professor;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author labccet
 */
public class PedidoProgressao extends javax.swing.JFrame {

    /**
     * Creates new form telaAluno
     */
    public PedidoProgressao() {
        initComponents();
        centralizarTela();
        areaAnexo4.setVisible(false);
        imagemAnexo4.setVisible(false);
        anexo4.setVisible(false);
        checkComprovante.setVisible(false);
//        calendario.setFormats(new String[] {"dd/MM/yyyy"});
//        calendario.setLinkDate(System.currentTimeMillis(), "Hoje é: {0}");
    }
     Aluno aluno;
     Professor professor;
    public PedidoProgressao(Professor professor){
        initComponents();
        this.professor= professor;
        preencherCampos();
//        calendario.setFormats(new String[] {"dd/MM/yyyy"});
//        calendario.setLinkDate(System.currentTimeMillis(), "Hoje é: {0}");
        centralizarTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nomeCompletoProfessorLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        matriculaAlunoLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        emailProfessorLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        telefoneAlunoLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cancelarBotao = new javax.swing.JButton();
        enviarBotao = new javax.swing.JButton();
        areaAnexo4 = new javax.swing.JPanel();
        imagemAnexo4 = new javax.swing.JLabel();
        anexo4 = new javax.swing.JLabel();
        areaAnexo3 = new javax.swing.JPanel();
        imagemAnexo3 = new javax.swing.JLabel();
        anexo3 = new javax.swing.JLabel();
        areaAnexo2 = new javax.swing.JPanel();
        imagemAnexo2 = new javax.swing.JLabel();
        anexo2 = new javax.swing.JLabel();
        areaAnexo1 = new javax.swing.JPanel();
        imagemAnexo1 = new javax.swing.JLabel();
        anexo1 = new javax.swing.JLabel();
        checkPortaria = new javax.swing.JCheckBox();
        checkRelatorio = new javax.swing.JCheckBox();
        checkReconhecimento = new javax.swing.JCheckBox();
        checkComprovante = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        siapeProfessorLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cargoProfessorLabel = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        telefoneCelularProfessorLabel = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lotacaoProfessorLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        categoriaComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        centroComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        escolaComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));

        jPanel2.setBackground(new java.awt.Color(56, 113, 156));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iBSI.png"))); // NOI18N

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Data de abertura:");

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Data de fechamento:");

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("dd/mm/yyyy");

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("dd/mm/yyyy");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("numero de protocolo");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("status");

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Data de fechamento:");

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("dd/mm/yyyy");

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("dd/mm/yyyy");

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Data de abertura:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(591, 591, 591)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel9))
                            .addComponent(jLabel8))
                        .addGap(148, 148, 148)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33))
                        .addGap(413, 413, 413)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addGap(138, 138, 138))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel31))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel32))))
                                .addGap(19, 19, 19))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel34))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel33))
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Nome:");

        nomeCompletoProfessorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeCompletoProfessorLabel.setText("Nome Completo do Professor");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Matrícula:");

        matriculaAlunoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        matriculaAlunoLabel.setText("123456789");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("E-mail:");

        emailProfessorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailProfessorLabel.setText("nome.sobrenome@uniriotec.br");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Telefone:");

        telefoneAlunoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telefoneAlunoLabel.setText("(21) 9-2222-2222");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Período:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("período");

        jLabel21.setText("X");

        cancelarBotao.setBackground(new java.awt.Color(56, 113, 156));
        cancelarBotao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelarBotao.setForeground(new java.awt.Color(255, 255, 255));
        cancelarBotao.setText("Voltar");
        cancelarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotaoActionPerformed(evt);
            }
        });

        enviarBotao.setBackground(new java.awt.Color(56, 113, 156));
        enviarBotao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enviarBotao.setForeground(new java.awt.Color(255, 255, 255));
        enviarBotao.setText("Enviar");
        enviarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarBotaoActionPerformed(evt);
            }
        });

        imagemAnexo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/documentoAnexar.png"))); // NOI18N

        anexo4.setText("Anexo 4");

        javax.swing.GroupLayout areaAnexo4Layout = new javax.swing.GroupLayout(areaAnexo4);
        areaAnexo4.setLayout(areaAnexo4Layout);
        areaAnexo4Layout.setHorizontalGroup(
            areaAnexo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaAnexo4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(areaAnexo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagemAnexo4)
                    .addComponent(anexo4))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        areaAnexo4Layout.setVerticalGroup(
            areaAnexo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaAnexo4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagemAnexo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(anexo4)
                .addGap(5, 5, 5))
        );

        imagemAnexo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/documentoAnexar.png"))); // NOI18N

        anexo3.setText("Anexo 3");

        javax.swing.GroupLayout areaAnexo3Layout = new javax.swing.GroupLayout(areaAnexo3);
        areaAnexo3.setLayout(areaAnexo3Layout);
        areaAnexo3Layout.setHorizontalGroup(
            areaAnexo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaAnexo3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(areaAnexo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imagemAnexo3)
                    .addComponent(anexo3))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        areaAnexo3Layout.setVerticalGroup(
            areaAnexo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaAnexo3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagemAnexo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anexo3)
                .addGap(5, 5, 5))
        );

        imagemAnexo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/documentoAnexar.png"))); // NOI18N

        anexo2.setText("Anexo 2");

        javax.swing.GroupLayout areaAnexo2Layout = new javax.swing.GroupLayout(areaAnexo2);
        areaAnexo2.setLayout(areaAnexo2Layout);
        areaAnexo2Layout.setHorizontalGroup(
            areaAnexo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaAnexo2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(areaAnexo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imagemAnexo2)
                    .addComponent(anexo2))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        areaAnexo2Layout.setVerticalGroup(
            areaAnexo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaAnexo2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagemAnexo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anexo2)
                .addGap(5, 5, 5))
        );

        imagemAnexo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/documentoAnexar.png"))); // NOI18N

        anexo1.setText("Anexo 1");

        javax.swing.GroupLayout areaAnexo1Layout = new javax.swing.GroupLayout(areaAnexo1);
        areaAnexo1.setLayout(areaAnexo1Layout);
        areaAnexo1Layout.setHorizontalGroup(
            areaAnexo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaAnexo1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(areaAnexo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imagemAnexo1)
                    .addComponent(anexo1))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        areaAnexo1Layout.setVerticalGroup(
            areaAnexo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaAnexo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagemAnexo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(anexo1)
                .addGap(5, 5, 5))
        );

        checkPortaria.setText("Portaria da última progressão funcional referente ao último nível da classe antecedente a  pleiteada ou do termo de posse");

        checkRelatorio.setText("Relatório das atividades por mim desenvolvidas no período em análise, para a  avaliação de desempenho");
        checkRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRelatorioActionPerformed(evt);
            }
        });

        checkReconhecimento.setText("Reconhecimento da CAPES da Instituição de Ensino da Titulação");

        checkComprovante.setText("Cópia do comprovante do Título de Doutor (Somente para a Classe D)");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("SIAPE:");

        siapeProfessorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        siapeProfessorLabel.setText("numeroSIAPE");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Cargo/Função:");

        cargoProfessorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cargoProfessorLabel.setText("Cargo/Função");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Lotação:");

        telefoneCelularProfessorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telefoneCelularProfessorLabel.setText("222222222");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Telefone: ");

        lotacaoProfessorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lotacaoProfessorLabel.setText("Lotação");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Categoria:");

        categoriaComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        categoriaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));
        categoriaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Centro:");

        centroComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        centroComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CCJP", "CCET", "IBIO" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Escola:");

        escolaComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        escolaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EIA", "EEP", "-" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(centroComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomeCompletoProfessorLabel)
                                    .addComponent(telefoneCelularProfessorLabel)
                                    .addComponent(emailProfessorLabel)
                                    .addComponent(categoriaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(155, 155, 155)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(escolaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(siapeProfessorLabel))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cargoProfessorLabel)))
                                        .addGap(447, 447, 447)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(matriculaAlunoLabel)
                                                .addGap(77, 77, 77)
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel20))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(telefoneAlunoLabel))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lotacaoProfessorLabel))))
                            .addComponent(checkRelatorio)
                            .addComponent(checkReconhecimento)
                            .addComponent(checkPortaria)
                            .addComponent(checkComprovante)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(areaAnexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(areaAnexo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(areaAnexo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(areaAnexo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(cancelarBotao)
                        .addGap(95, 95, 95)
                        .addComponent(enviarBotao)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(nomeCompletoProfessorLabel)
                            .addComponent(jLabel12)
                            .addComponent(siapeProfessorLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(emailProfessorLabel)
                            .addComponent(jLabel16)
                            .addComponent(cargoProfessorLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(matriculaAlunoLabel)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(telefoneAlunoLabel))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(telefoneCelularProfessorLabel)
                        .addComponent(lotacaoProfessorLabel)
                        .addComponent(jLabel24)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(categoriaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(escolaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(centroComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(areaAnexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaAnexo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaAnexo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaAnexo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 27, Short.MAX_VALUE)
                .addComponent(checkRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkReconhecimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkPortaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkComprovante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBotao)
                    .addComponent(enviarBotao))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencherCampos(){
        emailProfessorLabel.setText(professor.getEmail());
        nomeCompletoProfessorLabel.setText(professor.getNome());
        siapeProfessorLabel.setText(professor.getSiape());
        telefoneCelularProfessorLabel.setText(professor.getTelefoneCelular());
        lotacaoProfessorLabel.setText(professor.getLotacao());
        cargoProfessorLabel.setText(professor.getCargo());
    }
    private void categoriaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaComboBoxActionPerformed
        categoriaComboBox.getSelectedItem();
        if (categoriaComboBox.getSelectedItem().equals("D")){
            areaAnexo4.setVisible(true);
            imagemAnexo4.setVisible(true);
            anexo4.setVisible(true);
            checkComprovante.setVisible(true);

        }
    }//GEN-LAST:event_categoriaComboBoxActionPerformed

    private void checkRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkRelatorioActionPerformed

    private void enviarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarBotaoActionPerformed
        if((checkRelatorio.isSelected())&& (checkPortaria.isSelected())&&(checkReconhecimento.isSelected())){
            if(checkComprovante.isVisible()){
                if(checkComprovante.isSelected()){
                    TelaProfessor novaTelaProfessor = new TelaProfessor(professor);
                    novaTelaProfessor.setVisible(true);
                    this.setVisible(false);
                    this.dispose();
            }
            }
            else{
                    TelaProfessor novaTelaProfessor = new TelaProfessor(professor);
                    novaTelaProfessor.setVisible(true);
                    this.setVisible(false);
                    this.dispose();
            }
//            
            
        }
        else{
            PreenchaDadosPopUp dadosIncompletos = new PreenchaDadosPopUp();
            dadosIncompletos.setVisible(true);
        }
        
    }//GEN-LAST:event_enviarBotaoActionPerformed

    private void cancelarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotaoActionPerformed
        TelaProfessor telaProfessor = new TelaProfessor(professor);
        telaProfessor.setVisible(true);
        this.setVisible(false);
        this.dispose(); ;
    }//GEN-LAST:event_cancelarBotaoActionPerformed
private void teste(){
//    Calendar calendar = calendario.getMonthView().getCalendar();
//    // starting today if we are in a hurry
//    calendar.setTime(new Date());
//    calendario.getMonthView().setLowerBound(calendar.getTime());
//    // end of next week
//    CalendarUtils.endOfWeek(calendar);
//    calendar.add(Calendar.WEEK_OF_YEAR);
//    calendario.getMonthView().setUpperBound(calendar.getTime());
//    Date testando = calendario.getDate();
//    System.out.println(testando);
}
    private void centralizarTela(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
        
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anexo1;
    private javax.swing.JLabel anexo2;
    private javax.swing.JLabel anexo3;
    private javax.swing.JLabel anexo4;
    private javax.swing.JPanel areaAnexo1;
    private javax.swing.JPanel areaAnexo2;
    private javax.swing.JPanel areaAnexo3;
    private javax.swing.JPanel areaAnexo4;
    private javax.swing.JButton cancelarBotao;
    private javax.swing.JLabel cargoProfessorLabel;
    private javax.swing.JComboBox categoriaComboBox;
    private javax.swing.JComboBox centroComboBox;
    private javax.swing.JCheckBox checkComprovante;
    private javax.swing.JCheckBox checkPortaria;
    private javax.swing.JCheckBox checkReconhecimento;
    private javax.swing.JCheckBox checkRelatorio;
    private javax.swing.JLabel emailProfessorLabel;
    private javax.swing.JButton enviarBotao;
    private javax.swing.JComboBox escolaComboBox;
    private javax.swing.JLabel imagemAnexo1;
    private javax.swing.JLabel imagemAnexo2;
    private javax.swing.JLabel imagemAnexo3;
    private javax.swing.JLabel imagemAnexo4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lotacaoProfessorLabel;
    private javax.swing.JLabel matriculaAlunoLabel;
    private javax.swing.JLabel nomeCompletoProfessorLabel;
    private javax.swing.JLabel siapeProfessorLabel;
    private javax.swing.JLabel telefoneAlunoLabel;
    private javax.swing.JLabel telefoneCelularProfessorLabel;
    // End of variables declaration//GEN-END:variables
}
