/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static controller.Gerenciador.obterAluno;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.time.LocalDate;
import model.entity.Aluno;
import model.requerimento.Requerimento;

/**
 *
 * @author tsuba
 */
public class PopupComentario extends javax.swing.JFrame {

    /**
     * Creates new form popupComentario
     */
    public PopupComentario() {
        initComponents();
        centralizarTela();

    }
    String tipoAtualizacao;
    Requerimento requerimento;
     public PopupComentario(Requerimento requerimento, String tipoAtualizacao) {
        initComponents();
        this.tipoAtualizacao = tipoAtualizacao;
        this.requerimento = requerimento;
        centralizarTela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentarioAreaTexto = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        okBotaoComentario = new javax.swing.JButton();
        cancelarBotaoComentario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        comentarioAreaTexto.setColumns(20);
        comentarioAreaTexto.setRows(5);
        jScrollPane1.setViewportView(comentarioAreaTexto);

        jLabel1.setText("Adicionar comentário:");

        okBotaoComentario.setText("OK");
        okBotaoComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBotaoComentarioActionPerformed(evt);
            }
        });

        cancelarBotaoComentario.setText("Cancelar");
        cancelarBotaoComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotaoComentarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(cancelarBotaoComentario)
                        .addGap(69, 69, 69)
                        .addComponent(okBotaoComentario)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBotaoComentario)
                    .addComponent(okBotaoComentario))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    private void centralizarTela(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    
    private void okBotaoComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBotaoComentarioActionPerformed
        if(comentarioAreaTexto.getText().equals("")||comentarioAreaTexto.getText().equals(" ")){
            PreenchaDadosPopUp alertaFaltaDados = new PreenchaDadosPopUp();
            alertaFaltaDados.setVisible(true);
        }
        else{
            escreverComentario();
            this.setVisible(false);
            this.dispose();
        }
        //TODO: Colocar a leitura do XML
    }//GEN-LAST:event_okBotaoComentarioActionPerformed

    private void cancelarBotaoComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotaoComentarioActionPerformed
        this.setVisible(false);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarBotaoComentarioActionPerformed
    public void escreverComentario(){
        String comentario = comentarioAreaTexto.getText();
        String resposta = requerimento.getResposta();
        String descricao = requerimento.getDescricao();
       
        switch(tipoAtualizacao){
            case "PENDENTE":{
                requerimento.setResposta(resposta+ "\nNota de Pendencia - " + String.valueOf(LocalDate.now()) + ":\n" + comentario);
                requerimento.setStatus("PENDENTE");
                controller.Gerenciador.analisaRequerimento(requerimento); 
                break;}
            case "ACEITO":{
                requerimento.setResposta(resposta+"\nNota de Aceitação - " + String.valueOf(LocalDate.now()) + ":\n" + comentario);
                requerimento.setStatus("CONCLUIDO");
                requerimento.setDataSolucao(String.valueOf(LocalDate.now()));
                controller.Gerenciador.analisaRequerimento(requerimento); break;}
            case "REJEITADO":{
                requerimento.setResposta( resposta+"\nNota de rejeição - " + String.valueOf(LocalDate.now()) + ":\n" + comentario);
                requerimento.setStatus("REJEITADO");
                requerimento.setDataSolucao(String.valueOf(LocalDate.now()));
                controller.Gerenciador.analisaRequerimento(requerimento); 
                break;}
            case "ATUALIZACAO":{requerimento.setDescricao(descricao + "\nNota de atualizacao - " + String.valueOf(LocalDate.now()) + ":\n" + comentario);
                controller.Gerenciador.analisaRequerimento(requerimento); 
                break;}
            default: break;
        }
               
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBotaoComentario;
    private javax.swing.JTextArea comentarioAreaTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okBotaoComentario;
    // End of variables declaration//GEN-END:variables
}
