/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static controller.Gerenciador.buscarRequerimentoProtocolo;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.entity.Professor;
import model.requerimento.Requerimento;

/**
 *
 * @author labccet
 */
public class TelaProfessor extends javax.swing.JFrame {

    /**
     * Creates new form telaAluno
     */
    public TelaProfessor() {

        initComponents();
        visibilidadeAbaProfessor(professor.getCargo());
        centralizarTela();

    }
    Professor professor;
    public TelaProfessor(Professor professor) {
        initComponents();
        this.professor = professor; 
        preencherTela();
        visibilidadeAbaProfessor(professor.getCargo());
        popularRequerimentosAlunos();
        popularRequerimentosAlunosPendentes();
        popularRequerimentosAlunosFinalizado();
        centralizarTela();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<String>();
        painelRequerimentosProfessores = new javax.swing.JTabbedPane();
        tabRequerimentoProfessores = new javax.swing.JScrollPane();
        tabelaRequerimentosDeProfessores = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaMeusRequerimentos = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        nomeCompletoProfessorLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        emailProfessorLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        telefoneCelularProfessorLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        painelTelaAluno1 = new javax.swing.JTabbedPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaRequerimentoAlunos = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelaRequerimentoAlunosPendentes = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelaRequerimentoAlunosFinalizados = new javax.swing.JTable();
        siapieProfessorLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        centroAcademicoProfessorLabel = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        regimeTrabalhoProfessorLabel = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lotacaoProfessorLabel = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        classeDocenteProfessorLabel = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        titulacaoProfessorLabel = new javax.swing.JLabel();
        quadradoAtualizacao = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        setinhaAtualizacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));

        jPanel2.setBackground(new java.awt.Color(56, 113, 156));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iBSI.png"))); // NOI18N

        logoutLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setText("Trocar de Usuário");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(937, 937, 937)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutLabel)
                        .addGap(31, 31, 31))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(63, 63, 63)
                        .addComponent(logoutLabel)
                        .addGap(44, 44, 44))))
        );

        lista.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Pedido de Afastamento", "Pedido de Progressão" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecionarRequerimento(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        painelRequerimentosProfessores.setBackground(new java.awt.Color(255, 255, 255));

        if("Professor".equals("Decano") || "Professor".equals("Chefe de Departamento")){
            tabelaRequerimentosDeProfessores = new javax.swing.JTable();
        }
        tabelaRequerimentosDeProfessores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Protocolo", "Nome Requerente", "Tipo", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaRequerimentosDeProfessores.setColumnSelectionAllowed(true);
        tabRequerimentoProfessores.setViewportView(tabelaRequerimentosDeProfessores);
        tabelaRequerimentosDeProfessores.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        painelRequerimentosProfessores.addTab("Requerimentos de Professores", tabRequerimentoProfessores);

        tabelaMeusRequerimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Protocolo", "Tipo", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaMeusRequerimentos.setColumnSelectionAllowed(true);
        jScrollPane4.setViewportView(tabelaMeusRequerimentos);
        tabelaMeusRequerimentos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        painelRequerimentosProfessores.addTab("Meus Requerimentos", jScrollPane4);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Nome:");

        nomeCompletoProfessorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeCompletoProfessorLabel.setText("Nome Completo do Professor");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("E-mail:");

        emailProfessorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailProfessorLabel.setText("nome.sobrenome@uniriotec.br");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Telefone:");

        telefoneCelularProfessorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telefoneCelularProfessorLabel.setText("(21) 9-2222-2222");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Matrícula SIAPE:");

        painelTelaAluno1.setBackground(new java.awt.Color(255, 255, 255));

        tabelaRequerimentoAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Protocolo", "Nome Requerente", "Tipo", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaRequerimentoAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaRequerimentoAlunosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabelaRequerimentoAlunos);
        tabelaRequerimentoAlunos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        painelTelaAluno1.addTab("Requerimentos de Alunos", jScrollPane5);

        tabelaRequerimentoAlunosPendentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Protocolo", "Nome Requerente", "Tipo", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaRequerimentoAlunosPendentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaRequerimentoAlunosPendentesMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tabelaRequerimentoAlunosPendentes);
        tabelaRequerimentoAlunosPendentes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        painelTelaAluno1.addTab("Requerimentos de Alunos Pendentes", jScrollPane6);

        tabelaRequerimentoAlunosFinalizados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Protocolo", "Nome Requerente", "Tipo", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaRequerimentoAlunosFinalizados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaRequerimentoAlunosFinalizadosMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tabelaRequerimentoAlunosFinalizados);
        tabelaRequerimentoAlunosFinalizados.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        painelTelaAluno1.addTab("Requerimentos de Alunos Finalizados", jScrollPane7);

        siapieProfessorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        siapieProfessorLabel.setText("SIAPE");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Centro Acadêmico:");

        centroAcademicoProfessorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        centroAcademicoProfessorLabel.setText("CCET");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Regime Trabalho:");

        regimeTrabalhoProfessorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        regimeTrabalhoProfessorLabel.setText("regimeTrabalho");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Lotação:");

        lotacaoProfessorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lotacaoProfessorLabel.setText("Escola de Informática Aplicada");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Classe docente:");

        classeDocenteProfessorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        classeDocenteProfessorLabel.setText("ClasseDocente");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Titulação:");

        titulacaoProfessorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titulacaoProfessorLabel.setText("Titulação");

        quadradoAtualizacao.setBackground(new java.awt.Color(255, 255, 255));
        quadradoAtualizacao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(56, 113, 156), 2, true));
        quadradoAtualizacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quadradoAtualizacaoMouseClicked(evt);
            }
        });

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));

        jLabel36.setText("Atualizar");

        setinhaAtualizacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N

        javax.swing.GroupLayout quadradoAtualizacaoLayout = new javax.swing.GroupLayout(quadradoAtualizacao);
        quadradoAtualizacao.setLayout(quadradoAtualizacaoLayout);
        quadradoAtualizacaoLayout.setHorizontalGroup(
            quadradoAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quadradoAtualizacaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addContainerGap())
            .addGroup(quadradoAtualizacaoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(quadradoAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setinhaAtualizacao)
                    .addComponent(jLabel35))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        quadradoAtualizacaoLayout.setVerticalGroup(
            quadradoAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quadradoAtualizacaoLayout.createSequentialGroup()
                .addGroup(quadradoAtualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quadradoAtualizacaoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel35))
                    .addGroup(quadradoAtualizacaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(setinhaAtualizacao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel36))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(painelTelaAluno1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                            .addComponent(painelRequerimentosProfessores)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeCompletoProfessorLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(emailProfessorLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(telefoneCelularProfessorLabel)))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(7, 7, 7)
                                .addComponent(siapieProfessorLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(centroAcademicoProfessorLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lotacaoProfessorLabel)))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(classeDocenteProfessorLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titulacaoProfessorLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(regimeTrabalhoProfessorLabel)))
                        .addGap(82, 82, 82)
                        .addComponent(quadradoAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(quadradoAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(siapieProfessorLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(centroAcademicoProfessorLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(regimeTrabalhoProfessorLabel)
                                    .addComponent(jLabel27)
                                    .addComponent(lotacaoProfessorLabel)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nomeCompletoProfessorLabel)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(emailProfessorLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(telefoneCelularProfessorLabel)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel29)
                                    .addComponent(classeDocenteProfessorLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titulacaoProfessorLabel)
                                    .addComponent(jLabel31))))))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(painelTelaAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelRequerimentosProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1087, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void preencherTela(){
        emailProfessorLabel.setText(professor.getEmail());
        nomeCompletoProfessorLabel.setText(professor.getNome());
        siapieProfessorLabel.setText(professor.getSiape());
        telefoneCelularProfessorLabel.setText(professor.getTelefoneCelular());
        centroAcademicoProfessorLabel.setText(professor.getCentroAcademico());
        classeDocenteProfessorLabel.setText(professor.getClasseDocente());
        titulacaoProfessorLabel.setText(professor.getTitulacao());
        regimeTrabalhoProfessorLabel.setText(professor.getRegimeTrabalho());
        
    }
    
    private void limparTabela(){
        DefaultTableModel model = (DefaultTableModel) tabelaRequerimentoAlunosPendentes.getModel();
        DefaultTableModel model2 = (DefaultTableModel) tabelaRequerimentoAlunosFinalizados.getModel();
        DefaultTableModel model3 = (DefaultTableModel) tabelaRequerimentoAlunos.getModel();

        model.setRowCount(0);
        model2.setRowCount(0);
        model3.setRowCount(0);

    }
    private void popularMeusRequerimentos(){ 
//        DefaultTableModel model = (DefaultTableModel) tabelaMeusRequerimentos.getModel();
//        ArrayList<Requerimento> requerimentos = controller.Gerenciador.buscarRequerimentoCPF(professor.getCpf());
//        Object rowData[] = new Object[3];
//        for (int i = 0; i < requerimentos.size(); i++) {
//            rowData[0] = requerimentos.get(i).getNumeroProtocolo();
//            rowData[1] = requerimentos.get(i).getTipoRequerimento();
//            rowData[2] = requerimentos.get(i).getStatus();
//            model.addRow(rowData);
//        }
    }
    private void popularRequerimentosAlunos(){
     DefaultTableModel model = (DefaultTableModel) tabelaRequerimentoAlunos.getModel();
        ArrayList<Requerimento> requerimentos = controller.Gerenciador.buscarRequerimentoAreaResponsavelProfessorDesignado(professor.getCpf());
        Object rowData[] = new Object[4];
        for (int i = 0; i < requerimentos.size(); i++) {
            rowData[0] = requerimentos.get(i).getNumeroRequerimento();
            rowData[1] = requerimentos.get(i).requerente.getNome();
            rowData[2] = requerimentos.get(i).getTipoRequerimento();
            rowData[3] = requerimentos.get(i).getStatus();
            model.addRow(rowData);
        }
    }
    
    private void popularRequerimentosAlunosFinalizado(){
        DefaultTableModel model = (DefaultTableModel) tabelaRequerimentoAlunosFinalizados.getModel();
        ArrayList<Requerimento> requerimentos = controller.Gerenciador.buscarRequerimentoAreaResponsavelProfessorFinalizado(professor.getCpf());
        Object rowData[] = new Object[4];
        for (int i = 0; i < requerimentos.size(); i++) {
            rowData[0] = requerimentos.get(i).getNumeroRequerimento();
            rowData[1] = requerimentos.get(i).requerente.getNome();
            rowData[2] = requerimentos.get(i).getTipoRequerimento();
            rowData[3] = requerimentos.get(i).getStatus();
            model.addRow(rowData);
        }
    }
    
    private void popularRequerimentosAlunosPendentes(){
     DefaultTableModel model = (DefaultTableModel) tabelaRequerimentoAlunosPendentes.getModel();
        ArrayList<Requerimento> requerimentos = controller.Gerenciador.buscarRequerimentoAreaResponsavelProfessorDesignadoPendente(professor.getCpf());
        Object rowData[] = new Object[4];
        for (int i = 0; i < requerimentos.size(); i++) {
            rowData[0] = requerimentos.get(i).getNumeroRequerimento();
            rowData[1] = requerimentos.get(i).requerente.getNome();
            rowData[2] = requerimentos.get(i).getTipoRequerimento();
            rowData[3] = requerimentos.get(i).getStatus();
            model.addRow(rowData);
        }
    }
    
    private void popularRequerimentosProfessores(){
//     DefaultTableModel model = (DefaultTableModel) tabelaRequerimentosDeProfessores.getModel();
//        ArrayList<Requerimento> requerimentos = controller.Gerenciador.buscarRequerimentoRequerenteProfessor();
//        Object rowData[] = new Object[3];
//        for (int i = 0; i < requerimentos.size(); i++) {
//            rowData[0] = requerimentos.get(i).getNumeroProtocolo();
//            rowData[1] = requerimentos.get(i).getTipoRequerimento();
//            rowData[2] = requerimentos.get(i).getStatus();
//            model.addRow(rowData);
//        }
    }

    
    private void centralizarTela() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }
    private void selecionarRequerimento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecionarRequerimento
        String titulo;
        JList list = (JList) evt.getSource();
        titulo = (String) list.getSelectedValue();
        if (evt.getClickCount() == 2) {
            if (titulo.equals("Pedido de Progressão")) {
                PedidoProgressao janelaPedidoProgressao = new PedidoProgressao(professor);
                janelaPedidoProgressao.setVisible(true);
                janelaPedidoProgressao.setTitle(titulo);
                this.setVisible(false);
            } else if (titulo.equals("Pedido de Afastamento")) {
                PedidoAfastamento janelaPedidoAfastamento = new PedidoAfastamento(professor);
                janelaPedidoAfastamento.setVisible(true);
                janelaPedidoAfastamento.setTitle(titulo);
                this.setVisible(false);

            }
        }

    }//GEN-LAST:event_selecionarRequerimento
   
    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        Login telaLogin = new Login();
        telaLogin.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void quadradoAtualizacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quadradoAtualizacaoMouseClicked
        limparTabela();
        popularRequerimentosAlunos();
        popularRequerimentosAlunosPendentes();
        popularRequerimentosAlunosFinalizado();       
        
    }//GEN-LAST:event_quadradoAtualizacaoMouseClicked

    private void tabelaRequerimentoAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaRequerimentoAlunosMouseClicked
        tabelaRequerimentoAlunos = (JTable) evt.getSource();
        
        if (evt.getClickCount() == 2) {
            int numeroLinha = tabelaRequerimentoAlunos.getSelectedRow();
            String numeroProtocolo = (String) tabelaRequerimentoAlunos.getValueAt(numeroLinha,0);
            String tipoRequerimento =(String) tabelaRequerimentoAlunos.getValueAt(numeroLinha,1);
            ArrayList<Requerimento> requerimento = buscarRequerimentoProtocolo(numeroProtocolo);
            RequerimentoGeralAnexoProfessorLeitura requerimentoAlunoLeitura;
            requerimentoAlunoLeitura = new RequerimentoGeralAnexoProfessorLeitura(requerimento.get(0),tipoRequerimento, professor);
            requerimentoAlunoLeitura.setVisible(true);
        }   

    }//GEN-LAST:event_tabelaRequerimentoAlunosMouseClicked

    private void tabelaRequerimentoAlunosPendentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaRequerimentoAlunosPendentesMouseClicked
    tabelaRequerimentoAlunosPendentes = (JTable) evt.getSource();
        
        if (evt.getClickCount() == 2) {
            int numeroLinha = tabelaRequerimentoAlunosPendentes.getSelectedRow();
            String numeroProtocolo = (String) tabelaRequerimentoAlunosPendentes.getValueAt(numeroLinha,0);
            String tipoRequerimento =(String) tabelaRequerimentoAlunosPendentes.getValueAt(numeroLinha,1);
            ArrayList<Requerimento> requerimento = buscarRequerimentoProtocolo(numeroProtocolo);
            RequerimentoGeralAnexoProfessorLeitura requerimentoAlunoLeitura;
            requerimentoAlunoLeitura = new RequerimentoGeralAnexoProfessorLeitura(requerimento.get(0),tipoRequerimento, professor);
            requerimentoAlunoLeitura.setVisible(true);
        }   
    }//GEN-LAST:event_tabelaRequerimentoAlunosPendentesMouseClicked

    private void tabelaRequerimentoAlunosFinalizadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaRequerimentoAlunosFinalizadosMouseClicked
        tabelaRequerimentoAlunosFinalizados = (JTable) evt.getSource();
        
        if (evt.getClickCount() == 2) {
            int numeroLinha = tabelaRequerimentoAlunosFinalizados.getSelectedRow();
            String numeroProtocolo = (String) tabelaRequerimentoAlunosFinalizados.getValueAt(numeroLinha,0);
            String tipoRequerimento =(String) tabelaRequerimentoAlunosFinalizados.getValueAt(numeroLinha,1);
            ArrayList<Requerimento> requerimento = buscarRequerimentoProtocolo(numeroProtocolo);
            RequerimentoGeralAnexoProfessorLeitura requerimentoAlunoLeitura;
            requerimentoAlunoLeitura = new RequerimentoGeralAnexoProfessorLeitura(requerimento.get(0),tipoRequerimento, professor);
            requerimentoAlunoLeitura.setVisible(true);
        }   


    }//GEN-LAST:event_tabelaRequerimentoAlunosFinalizadosMouseClicked

    public void visibilidadeAbaProfessor(String cargo) {
        if (!cargo.equals("Decano") && !cargo.equals("Chefe de Departamento")) {
            painelRequerimentosProfessores.remove(tabRequerimentoProfessores);     
        }

    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel centroAcademicoProfessorLabel;
    private javax.swing.JLabel classeDocenteProfessorLabel;
    private javax.swing.JLabel emailProfessorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JList<String> lista;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel lotacaoProfessorLabel;
    private javax.swing.JLabel nomeCompletoProfessorLabel;
    private javax.swing.JTabbedPane painelRequerimentosProfessores;
    private javax.swing.JTabbedPane painelTelaAluno1;
    private javax.swing.JPanel quadradoAtualizacao;
    private javax.swing.JLabel regimeTrabalhoProfessorLabel;
    private javax.swing.JLabel setinhaAtualizacao;
    private javax.swing.JLabel siapieProfessorLabel;
    private javax.swing.JScrollPane tabRequerimentoProfessores;
    private javax.swing.JTable tabelaMeusRequerimentos;
    private javax.swing.JTable tabelaRequerimentoAlunos;
    private javax.swing.JTable tabelaRequerimentoAlunosFinalizados;
    private javax.swing.JTable tabelaRequerimentoAlunosPendentes;
    private javax.swing.JTable tabelaRequerimentosDeProfessores;
    private javax.swing.JLabel telefoneCelularProfessorLabel;
    private javax.swing.JLabel titulacaoProfessorLabel;
    // End of variables declaration//GEN-END:variables
}
